name: PROD CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rohitcdevops
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t rohitcdevops/gallery:latest \
                       -t rohitcdevops/gallery:${{ github.run_number }} .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push rohitcdevops/gallery:latest
          docker push rohitcdevops/gallery:${{ github.run_number }}
